// src/components/BibleMenu/constants.js
// Дані про книги Біблії для навігації
export const BOOK_CATEGORIES = [
  {
    id: "old-testament-books",
    label: "Книги Старого Заповіту",
    testament: "old-testament",
    items: [
      { full: "Буття", short: "Бут", internalKey: "genesis", chapters: 50 },
      { full: "Вихід", short: "Вих", internalKey: "exodus", chapters: 40 },
      { full: "Левит", short: "Лев", internalKey: "leviticus", chapters: 27 },
      { full: "Числа", short: "Чис", internalKey: "numbers", chapters: 36 },
      { full: "Повторення Закону", short: "Втор", internalKey: "deuteronomy", chapters: 34 },
      { full: "Ісуса Навина", short: "Нав", internalKey: "joshua", chapters: 24 },
      { full: "Суддів", short: "Суд", internalKey: "judges", chapters: 21 },
      { full: "Рут", short: "Рут", internalKey: "ruth", chapters: 4 },
      { full: "1 Самуїлова", short: "1Сам", internalKey: "1_samuel", chapters: 31 },
      { full: "2 Самуїлова", short: "2Сам", internalKey: "2_samuel", chapters: 24 },
      { full: "1 Царів", short: "1Цар", internalKey: "1_kings", chapters: 22 },
      { full: "2 Царів", short: "2Цар", internalKey: "2_kings", chapters: 25 },
      { full: "1 Хронік", short: "1Хр", internalKey: "1_chronicles", chapters: 29 },
      { full: "2 Хронік", short: "2Хр", internalKey: "2_chronicles", chapters: 36 },
      { full: "Ездри", short: "Езд", internalKey: "ezra", chapters: 10 },
      { full: "Неемії", short: "Неем", internalKey: "nehemiah", chapters: 13 },
      { full: "Естер", short: "Ест", internalKey: "esther", chapters: 10 },
      { full: "Йова", short: "Йов", internalKey: "job", chapters: 42 },
      { full: "Псалми", short: "Пс", internalKey: "psalms", chapters: 150 },
      { full: "Приповісті", short: "Пр", internalKey: "proverbs", chapters: 31 },
      { full: "Екклезіяст", short: "Ек", internalKey: "ecclesiastes", chapters: 12 },
      { full: "Пісня над Піснями", short: "Пісн", internalKey: "song_of_solomon", chapters: 8 },
      { full: "Ісаї", short: "Іс", internalKey: "isaiah", chapters: 66 },
      { full: "Єремії", short: "Єр", internalKey: "jeremiah", chapters: 52 },
      { full: "Плач Єремії", short: "Плач", internalKey: "lamentations", chapters: 5 },
      { full: "Єзекіїля", short: "Єз", internalKey: "ezekiel", chapters: 48 },
      { full: "Даниїла", short: "Дан", internalKey: "daniel", chapters: 12 },
      { full: "Осії", short: "Ос", internalKey: "hosea", chapters: 14 },
      { full: "Йоіла", short: "Йоіл", internalKey: "joel", chapters: 3 },
      { full: "Амоса", short: "Ам", internalKey: "amos", chapters: 9 },
      { full: "Овдія", short: "Ов", internalKey: "obadiah", chapters: 1 },
      { full: "Йони", short: "Йона", internalKey: "jonah", chapters: 4 },
      { full: "Михея", short: "Мих", internalKey: "micah", chapters: 7 },
      { full: "Наума", short: "Наум", internalKey: "nahum", chapters: 3 },
      { full: "Авакума", short: "Авак", internalKey: "habakkuk", chapters: 3 },
      { full: "Софонії", short: "Соф", internalKey: "zephaniah", chapters: 3 },
      { full: "Огія", short: "Ог", internalKey: "haggai", chapters: 2 },
      { full: "Захарії", short: "Зах", internalKey: "zechariah", chapters: 14 },
      { full: "Малахії", short: "Мал", internalKey: "malachi", chapters: 4 },
    ],
  },
  {
    id: "new-testament-books",
    label: "Книги Нового Заповіту",
    testament: "new-testament",
    items: [
      { full: "Матвія", short: "Мт", internalKey: "matthew", chapters: 28 },
      { full: "Марка", short: "Мк", internalKey: "mark", chapters: 16 },
      { full: "Луки", short: "Лк", internalKey: "luke", chapters: 24 },
      { full: "Івана", short: "Ів", internalKey: "john", chapters: 21 },
      { full: "Дії", short: "Дії", internalKey: "acts", chapters: 28 },
      { full: "Римлян", short: "Рим", internalKey: "romans", chapters: 16 },
      { full: "1 Коринтян", short: "1Кор", internalKey: "1_corinthians", chapters: 16 },
      { full: "2 Коринтян", short: "2Кор", internalKey: "2_corinthians", chapters: 13 },
      { full: "Галатів", short: "Гал", internalKey: "galatians", chapters: 6 },
      { full: "Ефесян", short: "Еф", internalKey: "ephesians", chapters: 6 },
      { full: "Филипʼян", short: "Флп", internalKey: "philippians", chapters: 4 },
      { full: "Колосян", short: "Кол", internalKey: "colossians", chapters: 4 },
      { full: "1 Солунян", short: "1Сол", internalKey: "1_thessalonians", chapters: 5 },
      { full: "2 Солунян", short: "2Сол", internalKey: "2_thessalonians", chapters: 3 },
      { full: "1 Тимофія", short: "1Тим", internalKey: "1_timothy", chapters: 6 },
      { full: "2 Тимофія", short: "2Тим", internalKey: "2_timothy", chapters: 4 },
      { full: "Тита", short: "Тит", internalKey: "titus", chapters: 3 },
      { full: "Филимона", short: "Флм", internalKey: "philemon", chapters: 1 },
      { full: "Євреїв", short: "Євр", internalKey: "hebrews", chapters: 13 },
      { full: "Якова", short: "Як", internalKey: "james", chapters: 5 },
      { full: "1 Петра", short: "1Пет", internalKey: "1_peter", chapters: 5 },
      { full: "2 Петра", short: "2Пет", internalKey: "2_peter", chapters: 3 },
      { full: "1 Івана", short: "1Ів", internalKey: "1_john", chapters: 5 },
      { full: "2 Івана", short: "2Ів", internalKey: "2_john", chapters: 1 },
      { full: "3 Івана", short: "3Ів", internalKey: "3_john", chapters: 1 },
      { full: "Юди", short: "Юд", internalKey: "jude", chapters: 1 },
      { full: "Обʼявлення", short: "Об", internalKey: "revelation", chapters: 22 },
    ],
  },
];
